version: 0.1.0
name: Practice
Authors: [ Optimus ]
main: com.optimus.practice.Practice
commands:
  practiceadmin:
    description: Admin Command
    aliases: [ pa, pracadmin ]
  wand:
  arena:
  spawnlocation:
    aliases: [ sp, spawnloc ]
  queue:
  request: